# Generated by Django 4.2.6 on 2023-11-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_blocked_users'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='category_preferences',
            field=models.ManyToManyField(related_name='category_preferences', to='articles.category'),
        ),
    ]
