# Generated by Django 4.2.6 on 2023-11-03 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_category_preferences'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='category_preferences',
            new_name='category_preference',
        ),
    ]
