# Generated by Django 4.2.6 on 2023-11-04 04:28

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alter_article_blocked_users_alter_article_dislike_and_more'),
        ('authentication', '0005_alter_user_category_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='category_preference',
            field=models.ManyToManyField(default=authentication.models.User.get_default_category_preference, related_name='category_preferences', to='articles.category'),
        ),
    ]
