# Generated by Django 4.2.6 on 2023-11-03 13:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0006_article_blocked_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, related_name='blocked_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='dislike',
            field=models.ManyToManyField(blank=True, related_name='disliked_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='liked_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
